### PR TITLE
change type of references and IDs from "number" to "integer"

### PR DESCRIPTION
**Pull request by weinand**
This PR applies the changes described in https://github.com/microsoft/debug-adapter-protocol/issues/62.

After applying the changes to the schema, the TypeScript generator did not produce any changes for the output.

But I expect changes for C# or C++ output of other generators.

@andrewcrawley please review

### CODE REVIEW

**Comment by int19h** [comment]
Could you also add `minimum` and `maximum` to these to enforce the valid range?

It's effectively int32, at least as Visual Studio (and hence any adapter that wants to be compatible with it) implements the protocol:

https://github.com/microsoft/VSDebugAdapterHost/issues/7
https://github.com/microsoft/VSDebugAdapterHost/issues/8

(+@gregg-miskelly to make sure I'm not misrepresenting anything here.)

I'm not sure if the generators for typed languages pay attention to these - but if they do, it might also help them use int32 or equivalent. If the default without min/max is int64, then a typed language might assume that large values are valid, and miss the fact that they cannot be accurately represented within the range of JavaScript doubles (we had this problem in the Python debug adapter, when we incorrectly tried to use the actual OS thread IDs as `threadId` - they'd often end up out-of-range on Linux).

**Comment by gregg-miskelly** [comment]
Correct, VS requires all of these to be 32-bit integers. So adding `minimum` and `maximum` values makes sense to me.

**Comment by gregg-miskelly** [comment]
Thinking about this more: since folks are more likely to read the [specification doc](https://microsoft.github.io/debug-adapter-protocol/specification) rather than the raw JSON, I am assuming that adding `minimum` and `maximum` will not necessarily be very helpful - maybe it will be helpful to some code generator out there. But if we really want to try and clarify this, it would be better to indicate it in the description. For example, for the `variablesReference` description, we could add a note at the end like:

```
"variablesReference": {
    "type": "number",
    "type": "integer",
    "description": "If an attribute 'variablesReference' exists and its value is > 0, the output contains objects which can be retrieved by passing 'variablesReference' to the 'variables' request. The value of 'variablesReference' should be less than or equal to 2147483647 (2^31 - 1)."
}
```

**Comment by int19h** [comment]
Ideally, it would be best to have it both in the spec and in the schema.

Having it in the schema is nice even if the code generators ignore it currently, because e.g. dynamically typed languages can directly use the schema to validate messages.

**Pull request merged**
