### PR TITLE
Remove non-generic DAP adapters from the list

### PR DESCRIPTION
**Pull request by 4e554c4c**
The list of DAP adapters is highly problematic in many ways. The index
page writes:

> The Debug Adapter Protocol makes it possible to implement a generic
> debugger for a development tool that can communicate with different
> debuggers via Debug Adapters. And Debug Adapters can be re-used across
> multiple development tools which significantly reduces the effort to
> support a new debugger in different tools.

However, most of the "adapters" in this list are VSCode specific, and
worse yet several don't actually implement DAP in any reasonable respect.
This makes it very difficult for non-VSCode tools to actually use these
adapters which is antithetical to the ideas behind DAP.

The problematic items can be broken down into multiple categories:
1. Adapters which implement DAP, but which completely unspecified on how
   to run.

   Examples include "Microsoft/vscode-cpptools" which, to run, you must
   [copy a file and run another random file with node](https://github.com/mfussenegger/nvim-dap/wiki/C-C---Rust-(gdb-via--vscode-cpptools))

2. "adapters" which are simply VSCode plugin shims to an actual
   DAP adapter.

   Examples include "vscode-byebug" which wraps the "bybug-dap" adapter.

In this PR I have removed both, as they are entirely not useful for
non-VSCode tools.

However, many of these adapters still retain useful code. I am open to
alternative solutions on how to deal with these projects. One way to
deal with them would be to add a "VSCode plugin only" column to the
list of projects. Then users of non-VSCode tools would be able to still
find the list helpful.
Another way to deal with this would be to remove each of these projects
for now, but also leave them each an issue upstream on how they could be
re-added (e.g. by adding instructions on how to actually use the DAP
server)
Finally, the VSCode project could release a project to easily extract
the DAP adapters and language servers from its plugins.

### CODE REVIEW

**Comment by connor4312** [comment]
I'm not clear on the purpose of removing these.

- If a user wants to find a debugger that works in their specific editor, they can search their editor's equivalent of a marketplace for that (e.g. VS Marketplace, Vim Awesome, JetBrains Marketplace...)
- If a developer wants to find example implementations of debug adapters, then preserving all of them in this list is useful.

Also, many of those you removed are in fact generic debuggers, though just packaged as vscode extensions. Just taking the first one off your list, for example, their executable is [`debugMain.js`](https://github.com/adelphes/android-dev-ext/blob/master/src/debugMain.js) which is a generic Node.js program: not editor specific, just not pre-packed for other editors.

**Comment by puremourning** [comment]
> In this PR I have removed both, as they are entirely not useful for
non-VSCode tools.

This isn't exactly true. While I share your frustration that most debug adapters are essentially undocumented, requiring DAP client authors to reverse-engineer the vscode plugins in order to determine how to launch the debug adapter itself and what the launch/attach arguments are, plenty of people (myself included) have done that for a large number of the adapters in the list. I know I'm not the only one. So to say "entirely not useful", is patently untrue.

It would indeed be nice if adapter authors ensured that their adapters conformed fully to the DAP spec, documented their launch and attach arguments, and documented how to start the debug adapter, so that users of "generic" DAP clients (which don't have adapoter-specifc handling for every adapter under the sun) can use them, but we have to accept that it's unlikely that will happen or be imposed. 

And removing them from this list will hardly help.

**Comment by 4e554c4c** [comment]
@connor4312 Yes, 100% agree about the marketplace. This should be a place to find editor specific integrations with different tools. But DAP is supposed to make it easier to create these for all editors, not just one.
I see your point about how this can be useful for devs creating DAP adapters, but not for users who wish to use them.

I really think you're missing the point about "packaging for another editor", lots of editors, like neovim, let you integrate a DAP adapter just by specifying an executable. If the requirement for using DAP is that it should be specifically packaged for every single editor then it falls short of the goal of being a generic protocol. This pushes an incredible amount of work onto users of a less-used editor (write a "marketplace package" for every single language they use). Taking language+debugging plugins  from an `n^2` problem to an `n+n` problem is the whole point of LSP+DAP, right?

I'll take android-dev-ext off of the list, but this shows my point quite well. [debugMain.js](https://github.com/adelphes/android-dev-ext/blob/master/src/debugMain.js) is in a perfectly reasonable place..... for a vscode plugin. Since I have never used vscode how am I supposed to use that when I am looking at the protocol in a neutral way? 

I agree with @puremourning a lot here. I mentioned later in my commit message that throwing away all of these links *would* be a huge waste because a lot of work has gone into them, so what can we do instead?
It would be a ton of work to insure that adapter authors conformed to the DAP spec, documented launch/attach options, etc. and this should absolutely not be a blocker on having a vscode plugin published. But we have a centralized knowledge repository right here!
Why not have documenting these options as a requirement to being added to the repo?

**Comment by 4e554c4c** [comment]
Anyway, as I mentioned later in my message it might be good to just add a column to this table that says "compatible with VSCode only". I could add that for the vscode plugins, and keep all of them for developer and reverse engineering work.
Then, the only requirement for the box being unchecked is for a adapter author or a contributor to this repo to document their options here or on the source repo.

**Comment by connor4312** [comment]
Perhaps instead of removing them, we add an additional column titled "Usage", which can link any editor plugin and documentation for using that implementation as a standalone DAP server

```
[VS Code](marketplace link), [DAP Server](documentation), [JetBrainz Plugin](...
```

**Comment by puremourning** [comment]
The idea that the documentation is per client is the problem. The servers should document their usage in general terms as should the clients. Then MxN is not required.

**Comment by 4e554c4c** [comment]
Right, this seems somewhat less scalable, every single editor would have to contribute documentation per-plugin for @connor4312 's suggestion

**Comment by connor4312** [comment]
In an idealistic view clients would have docs that describe how to plug into a DAP server, server would have the same, and users would connect them. But that is not how most developers use DAP--generally a DA is bundled in a plugin or bundle that is installed via tooling or UI offered by the editor. Of course, this is not the _only_ way to do things, but it's a major way.

(VS Code itself does not expose a way to connect to a generic DAP server, but maybe it should, feel free to open an issue on the VS Code repo if you have ideas for how this should work 🙂)

If this documentation is for people who want to use debuggers in their editors, then linking server documentation alongside client extensions seems more useful than removing them or marking them "vs code only" -- to @4e554c4c's previous point:

> This should be a place to find editor specific integrations with different tools. But DAP is supposed to make it easier to create these for all editors, not just one.

I don't think an MxN is less scalable -- generally the author of the extension will be the one maintaining and publishing the linked documentation/extension, and PR'ing a link when a new target is added is not expensive.

**Comment by weinand** [comment]
@connor4312 above you said:
> (VS Code itself does not expose a way to connect to a generic DAP server without any extensions, but maybe it should, feel free to open an issue on the VS Code repo if you have ideas for how this should work 🙂)

Actually, VS Code has a [documented](https://code.visualstudio.com/api/extension-guides/debugger-extension#development-setup-for-mock-debug) way to connect to a generic DAP server:
If you add a `debugServer` port property to a launch config, VS Code will ignore the `type` property in the launch config and tries to open a socket connection.
Since this bypasses all extension code, it requires that the DA can deal with incomplete launch configs and that it supports a "server mode" (indicated by a `--server=12345`  argument).

**Comment by puremourning** [comment]
In terms of how to proceed, I honestly think that removing them from the list is extremely unhelpful. Encouraging adapter authors to document the properties of the launch and attach requests would be extremely useful for maintainers of DAP clients, and as you say extensionless usage in vscode.

Stating that it's a requirement upon DAP client authors that they write code for each and every debug adapter that may exist ever is also, I think, unhelpful.

We can't make it a hard requirement on adapter authors of course (they can and will do whatever they like). Frequently if/when I report bugs adapters I get a response like "first and foremost this is a vscode plugin, so shrug...". 

I think the only, let's say, canonical way to "solve" this would be to require that the launch/attach arguments are defined in a message exchange on startup. For example, it could be a requirement of servers that they provide JSON schema (or something) describing their launch and attach configurations, which clients can read and validate or perhaps use to provide autocompletion in their own configuration systems. This is my ideal situation. Ironically, vscode extensions often contain something close to this (in the `contributes.debuggers` section), though it double-confuses users because it refers to the configuration entered into `launch.json` which is often _not_ the same as the configuration supplied in the launch/attach requests.

**Comment by puremourning** [comment]
I realise that the exchange on startup of the adapter isn't ideal at all, because it's too late in the day. In the sense that once the adapter is started, the user already typed in or set up their configuration, so that suggestion won't work either, sorry :)

**Comment by mfussenegger** [comment]
I think the proposed removal goes way too far. Many of these adapters work just fine with other clients.

But I'd propose to remove those who are essentially non-functional without custom protocol extensions. So far only vscode-js-debug comes to mind - as far as I'm aware you cannot use set functioning breakpoints without a custom protocol extension. If I am not mistaken it requires breakpoints to be set on a sub-session, which are communicated via a custom reverse request.


Otherwise I agree that ideally debug adapters would have some editor agnostic documentation:

1) How to launch it. What's the executable, what are the supported CLI parameters. (Some don't even support a `---help` or something like that)
2) Which transport they support/expect. stdio, TCP, others? This is somewhat related to 1)
3) Supported configuration options for `launch` and `attach`


I think debugpy is a good example of how it could be done. It does a fairly good job of that:

 1) https://github.com/microsoft/debugpy/wiki/Command-Line-Reference
 2) https://github.com/microsoft/debugpy/wiki/DAP-Client-reference#starting-debugpy-for-launch-scenario
 3) https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings


Maybe the adapter list could have two or three more columns with links to these type of documentation, to encourage debug adapter authors to create them?

Not sure. A lot of this is done by volunteers in their free time and they can do whatever they want.

**Comment by puremourning** [comment]
> Maybe the adapter list could have two or three more columns with links to these type of documentation, to encourage debug adapter authors to create them?

This is a great idea.

**Comment by int19h** [comment]
> I'd propose to remove those who are essentially non-functional without custom protocol extensions.

debugpy is an interesting case here. If multiprocess debugging is enabled, and the process being debugged does spawn child processes, the debug session will be broken unless the client is prepared to handle the custom message to attach to the spawned process (as it will not actually run any code until attached to). And multiprocess support is enabled by default; you have to disable it via `"subProcess": false` in the launch/attach request. So out of the box, it's technically non-functional unless you configure it just right.

OTOH we'd like to keep that default, because most users *are* on VSCode at the end of the day, and not requiring them to fiddle with settings for extremely common cases like debugging Django or Flask with auto-reload is desirable. Besides, it's been around for a while now, so changing it would be a breaking change - especially seeing how we have many consumers who are wrapping debugpy and generating custom configs for it with expectations of certain behavior.

Of course, the best solution to this would be some kind of standardization for multiproc debugging in general. But that seems unlikely to happen anytime soon, so what is the best way to mitigate it? From the perspective of client maintainers, do you consider the current state of affairs acceptable?

**Comment by int19h** [comment]
> I realise that the exchange on startup of the adapter isn't ideal at all, because it's too late in the day. In the sense that once the adapter is started, the user already typed in or set up their configuration

Not necessarily. This is the case in most (all?) clients today, I think; but it's entirely possible to start the adapter and communicate with it without ever issuing a launch/attach request. So long as querying the schema is also permissible in that state, I could see the client starting with *only* the knowledge of the adapter it needs to launch (i.e. "type" in launch.json or its equivalent). From there it can already start the adapter, query the schema for launch, shut it down, and offer completions etc.

Attach is a bit trickier because the client might not be starting the adapter at all in that scenario. So long as it has enough info to connect to the adapter, though, it can still connect-query-disconnect. This is somewhat hampered by the lack of a standardized schema for remote DAP connections over IP, but clients already have to deal with this in practice in other cases.

**Comment by connor4312** [comment]
I've made a PR to adjust the table with a "Usage" column in https://github.com/microsoft/debug-adapter-protocol/pull/260, following this discussion.

I opted for a single usage column rather than a column per editor as that could quickly get into a horizontal scrolling scenario with lots of editors.

**Comment by puremourning** [comment]
@mfussenegger's experience matches mine; I think of debugpy as a generally good DAP citizen in most respects.

**Comment by 4e554c4c** [comment]
I think that #260 is a great start, and I'm closing in favor of it. Thanks so much for all of the discussion here :slightly_smiling_face:

**Pull request closed without merging**
