### PR TITLE
Remove extra line breaks

### PR DESCRIPTION
**Pull request by rillig**

### CODE REVIEW

**Comment by rillig** [comment]
> Lines breaks are intentional in these comments

Oh, that comes as a surprise to me. Could you enlighten me what the below line break means?

> is about to start and <linebreak>
> provides additional information for

To me, this line break looks completely arbitrary, and [in the rendered document](https://microsoft.github.io/debug-adapter-protocol/specification#Events_ProgressStart) it is not only a line break but instead a paragraph break, which makes it look even stranger.

**Comment by connor4312** [comment]
actually, nevermind, reading thought these do look like they're paragraph breaks. I thought there was manual wrapping that would be used in code comments with single line breaks being ignored in the markdown rendering, but this is not the case.

**Comment by connor4312** [comment]
I think you will need to update the PR though since it conflicts with the ones we merged from you earlier 🙂

**Comment by connor4312** [comment]
Thanks!

**Pull request merged**
