### PR TITLE
Added OpenQASM DAP protocol implementation

### PR DESCRIPTION
**Pull request by sergeysalata**
OpenQASM is assembler language for quantum computers. New of DAP protocol for OpenQASM has been added.

### CODE REVIEW

**Review by Wesswoody88 — APPROVED** [review]

**Comment by connor4312** [comment]
Your PR seems to be based on the gh-pages branch rather than main -- can you rebase?

**Comment by sergeysalata** [comment]
> Your PR seems to be based on the gh-pages branch rather than main -- can you rebase?

somehow in 'master' branch link in 'adapters.md' points to 'gh-pages' branch. why?

**Comment by connor4312** [comment]
Ah, thanks for pointing that out, I'll fix it.

`gh-pages` is where the site is published from, but we stage our changes in master and only push to gh-pages during release. It looks like we were not careful enough with PRs and some were made directly to gh-pages. I'll add a workflow to avoid that in the future.

**Review by connor4312 — APPROVED** [review]

**Review by Tyriar — APPROVED** [review]

**Comment by sergeysalata** [comment]
Will it published on web https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/ ?

**Comment by sergeysalata** [comment]
> Yes, at the end of this month

seems not yet.

**Pull request merged**
